> A chain

                         LGTENLY FQSMDLRVQE LIKLICNVQA 
MEEMMMEMKY NTKKAPLGKL TVAQIKAGYQ SLKKIEDCIR AGQHGRALME 
ACNEFYTRIP HDFGLRTPPL IRTQKELSEK IQLLEALGDI EIAIKLVKTE 
LQSPEHPLDQ HYRNLHCALR PLDHESYEFK VISQYLQSTH APTHSDYTMT 
LLDLFEVEKD GEKEAFREDL HNRMLLWHGS RMSNWVGILS HGLRIAHPEA 
PITGYMFGKG IYFADMSSKS ANYCFASRLK NTGLLLLSEV ALGQCNELLE 
ANPKAEGLLQ GKHSTKGLGK MAPSSAHFVT LNGSTVPLGP ASDTGILGYT 
LNYNEYIVYN PNQVRMRYLL KVQFNF
